version: "3.8"

services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: pg-admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: bms
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
